# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bec657150081b6b26fde78080f4dd325adda39e00e4240a99f2ba5b7cd91bd9e40c93770c305e7251e981affa0d614169e4daadfae42f8a42a22aae45b3dc132

test:
  secret_key_base: d3feb8685bdd1e39a807846e38c5c89479ae0343a2a7593c9484cc84d509fb22496afff3a0430f6dfae072e158b6c2632926e0621e71cbc5ba02cc21a3703555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
